# Generated by Django 3.2 on 2021-12-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangofrontapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
